# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Create mongoDB Docker container      
      run: sudo docker run -d -p 27017:27017 mongo:latest
    - name: Add links data
      run: mongoimport --type csv -d recommender -c link --headerline --columnsHaveTypes --drop ./resources/links.csv
    - name: Add rating data
      run: mongoimport --type csv -d recommender -c review --headerline --drop ./resources/ratings.csv
    - name: Add movies_corrected data
      run: mongoimport --type csv -d recommender -c movie --headerline --drop ./resources/movies_corrected.csv
    - name: Add movie_poster data
      run: mongoimport --type csv -d recommender -c poster --headerline --drop ./resources/movie_poster.csv
    - name: Add users data
      run: mongoimport --type csv -d recommender -c user --headerline --drop ./resources/users.csv   

    - name: Build with Maven
      run: mvn package -Dmaven.test.failure.ignore=true
    
        
   
